# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qsaxC <- function(n) {
    .Call('_streamflow_qsaxC', PACKAGE = 'streamflow', n)
}

saxsymbC <- function(s, a) {
    .Call('_streamflow_saxsymbC', PACKAGE = 'streamflow', s, a)
}

mindistC <- function(psx, psy, a, n) {
    .Call('_streamflow_mindistC', PACKAGE = 'streamflow', psx, psy, a, n)
}

paaC <- function(s, w) {
    .Call('_streamflow_paaC', PACKAGE = 'streamflow', s, w)
}

naC <- function(x) {
    .Call('_streamflow_naC', PACKAGE = 'streamflow', x)
}

dsaxC <- function(x, y, w = 6, alpha = 9) {
    .Call('_streamflow_dsaxC', PACKAGE = 'streamflow', x, y, w, alpha)
}

saxvec <- function(x, m, w = 6, alpha = 9) {
    .Call('_streamflow_saxvec', PACKAGE = 'streamflow', x, m, w, alpha)
}

deucC <- function(x, y) {
    .Call('_streamflow_deucC', PACKAGE = 'streamflow', x, y)
}

eucvec <- function(x, m) {
    .Call('_streamflow_eucvec', PACKAGE = 'streamflow', x, m)
}

dcplxC <- function(x, y) {
    .Call('_streamflow_dcplxC', PACKAGE = 'streamflow', x, y)
}

cplxvec <- function(x, m) {
    .Call('_streamflow_cplxvec', PACKAGE = 'streamflow', x, m)
}

dcidC <- function(x, y) {
    .Call('_streamflow_dcidC', PACKAGE = 'streamflow', x, y)
}

cidvec <- function(x, m) {
    .Call('_streamflow_cidvec', PACKAGE = 'streamflow', x, m)
}

eucdm <- function(m) {
    .Call('_streamflow_eucdm', PACKAGE = 'streamflow', m)
}

saxdm <- function(m, w = 6, alpha = 9) {
    .Call('_streamflow_saxdm', PACKAGE = 'streamflow', m, w, alpha)
}

ciddm <- function(m) {
    .Call('_streamflow_ciddm', PACKAGE = 'streamflow', m)
}

